[package]
name = "example-server"
version = "0.1.0"
edition = "2021"

[dependencies]
dff = { path = "../../../rust" }
tokio = { version = "1.42", features = ["full"] }
anyhow = "1.0"
env_logger = "0.11"
rand = "0.8"